### ISSUE TITLE
Errot while reading CX file

### ISSUE THREAD

**Issue by KeyTals** [shitohana/BismarkPlot#7]
Hello,

Thank you creating very useful tool, I am trying to run metagene module but getting error which reading the CX file.

Here is my command

bismarkplot-metagene --dir test_plot -o test -g Macaca_mulatta.Mmul_10.110.chr.gff3  -r gene -f 2000 -m 4000  -u 500 -d 500 -w 1000 -b 1000000 --line --heatmap --box --violin --dpi 200 -F pdf -S 50 -c 4 RP1.CX_report.txt

this is the log 

Genome read from Macaca_mulatta.Mmul_10.110.chr.gff3
Reading from RP1.CX_report.txt
Error happened. Please open an issue at GitHub with Traceback from file: ZK12_plot/error12_21_09:44.txt

Here is the error

Traceback (most recent call last):
  File "/mnt/projects/ngs_dev/talsaniaks/anaconda/3.9/lib/python3.9/site-packages/bismarkplot/console_metagene.py", line 60, in main
    bismark = MetageneFiles.from_list(
  File "/mnt/projects/ngs_dev/talsaniaks/anaconda/3.9/lib/python3.9/site-packages/bismarkplot/BismarkPlot.py", line 1482, in from_list
    samples = [Metagene.from_file(file, genome, upstream_windows, gene_windows,
  File "/mnt/projects/ngs_dev/talsaniaks/anaconda/3.9/lib/python3.9/site-packages/bismarkplot/BismarkPlot.py", line 1482, in <listcomp>
    samples = [Metagene.from_file(file, genome, upstream_windows, gene_windows,
  File "/mnt/projects/ngs_dev/talsaniaks/anaconda/3.9/lib/python3.9/site-packages/bismarkplot/BismarkPlot.py", line 876, in from_file
    bismark_df = cls.__read_bismark_batches(file, genome,
  File "/mnt/projects/ngs_dev/talsaniaks/anaconda/3.9/lib/python3.9/site-packages/bismarkplot/BismarkPlot.py", line 999, in __read_bismark_batches
    df = process_batch(df)
  File "/mnt/projects/ngs_dev/talsaniaks/anaconda/3.9/lib/python3.9/site-packages/bismarkplot/BismarkPlot.py", line 956, in process_batch
    return (
  File "/mnt/projects/ngs_dev/talsaniaks/anaconda/3.9/lib/python3.9/site-packages/polars/lazyframe/frame.py", line 1706, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ComputeError: cannot cast numeric types to 'Categorical'

Also here are the few lines from my CX report, i have not filtered it for min coverage.

1	574	+	0	1	CHH	CCC
1	575	+	0	1	CHH	CCT
1	576	+	0	1	CHH	CTC
1	578	+	0	1	CHG	CTG
1	594	+	0	1	CHH	CTT
1	604	+	0	1	CHH	CTT
1	608	+	0	1	CHH	CAT
1	623	+	0	1	CHH	CAC

Thank you,
Keyur

**Comment by KeyTals** [comment]
Hello,

I was able to parse file from there and thank you for update but now getting following error, Do i need to have "chr" as prefix to fix this?

Traceback (most recent call last):
  File "/mnt/projects/ngs_dev/talsaniaks/anaconda/3.9/lib/python3.9/site-packages/bismarkplot/console_metagene.py", line 60, in main
    bismark = MetageneFiles.from_list(
  File "/mnt/projects/ngs_dev/talsaniaks/anaconda/3.9/lib/python3.9/site-packages/bismarkplot/BismarkPlot.py", line 1482, in from_list
    samples = [Metagene.from_file(file, genome, upstream_windows, gene_windows,
  File "/mnt/projects/ngs_dev/talsaniaks/anaconda/3.9/lib/python3.9/site-packages/bismarkplot/BismarkPlot.py", line 1482, in <listcomp>
    samples = [Metagene.from_file(file, genome, upstream_windows, gene_windows,
  File "/mnt/projects/ngs_dev/talsaniaks/anaconda/3.9/lib/python3.9/site-packages/bismarkplot/BismarkPlot.py", line 876, in from_file
    bismark_df = cls.__read_bismark_batches(file, genome,
  File "/mnt/projects/ngs_dev/talsaniaks/anaconda/3.9/lib/python3.9/site-packages/bismarkplot/BismarkPlot.py", line 1012, in __read_bismark_batches
    batches = bismark.next_batches(cpu)
  File "/mnt/projects/ngs_dev/talsaniaks/anaconda/3.9/lib/python3.9/site-packages/polars/io/csv/batched_reader.py", line 136, in next_batches
    batches = self._reader.next_batches(n)
polars.exceptions.ComputeError: could not parse `X` as dtype `i64` at column 'column_1' (column number 1)

Keyur

**Comment by KeyTals** [comment]
It created CG+_line-plot.pdf plot and then error out with folllowing error.

Traceback (most recent call last):
  File "/mnt/projects/ngs_dev/talsaniaks/anaconda/3.9/lib/python3.9/site-packages/bismarkplot/console_metagene.py", line 85, in main
    fig = filtered.heat_map(args.hresolution, args.vresolution).draw()
  File "/mnt/projects/ngs_dev/talsaniaks/anaconda/3.9/lib/python3.9/site-packages/bismarkplot/BismarkPlot.py", line 1540, in heat_map
    return HeatMapFiles([sample.heat_map(nrow, ncol) for sample in self.samples], self.labels)
  File "/mnt/projects/ngs_dev/talsaniaks/anaconda/3.9/lib/python3.9/site-packages/bismarkplot/BismarkPlot.py", line 1540, in <listcomp>
    return HeatMapFiles([sample.heat_map(nrow, ncol) for sample in self.samples], self.labels)
  File "/mnt/projects/ngs_dev/talsaniaks/anaconda/3.9/lib/python3.9/site-packages/bismarkplot/BismarkPlot.py", line 1133, in heat_map
    return HeatMap(bismark.bismark, nrow, order=None, **bismark.metadata)
  File "/mnt/projects/ngs_dev/talsaniaks/anaconda/3.9/lib/python3.9/site-packages/bismarkplot/BismarkPlot.py", line 1336, in __init__
    hm_data = (
  File "/mnt/projects/ngs_dev/talsaniaks/anaconda/3.9/lib/python3.9/site-packages/polars/lazyframe/frame.py", line 1706, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ComputeError: cannot cast List type (inner: 'Int64', to: 'Int32')


Keyur
